spring.application.name=financial_planner_api
# Disable serving static resources so the application behaves as an API-only backend
spring.web.resources.add-mappings=false

# Server configuration
server.port=8080

# Enable debug logging to see what's happening
logging.level.root=INFO
logging.level.com.not_found.financial_planner_api=DEBUG
