package com.not_found.financial_planner_api.model;

import lombok.Getter;
import lombok.Setter;

/**
 * Represents a financial account in the system.
 * Uses Lombok annotations for automatic getter and setter generation.
 */
@Getter
@Setter
public class Account {
    private String id; // Unique identifier for the account
    private String customerName; // Name of the account holder
    private String dateJoined; // Date when the account was created
    private boolean subscriptionPlan; // true for Premium, false for Basic
    private String accountName; // Name of the account (e.g., "Checking", "Savings")
    private double balance; // Current balance of the account
    private int age; // Age of the account holder
    private String gender; // Gender of the account holder
    private String phoneNumber; // Contact phone number
    private String email; // Contact email address
    private String dob; // Date of birth

    /** Default constructor for JPA and JSON serialization */
    public Account() {}

    /**
     * Constructor for creating a new account
     * @param name Name of the account (e.g., "Checking", "Savings")
     * @param balance Initial balance of the account
     */
    public Account(double balance, String customerName, boolean subscriptionType, String dateJoined) {
        this.balance = balance;
        this.customerName = customerName;
        this.subscriptionPlan = subscriptionType;
        // this.dateJoined = dateJoined;
        // this.age = age;
        // this.gender = gender;
        // this.phoneNumber = phoneNumber;
        // this.email = email;
        // this.dob = dob;
    }
    public String getSubscriptionPlan(){
        if (subscriptionPlan) {
            return "Premium";
        } else {
            return "Basic";
        }
    }

    // Getters and setters are generated by Lombok (@Getter / @Setter)
}
