package com.not_found.financial_planner_api.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Account {
    private long id;
    private String name;
    private double balance;

    public Account() {}

    public Account(long id, String name, double balance) {
        this.id = id;
        this.name = name;
        this.balance = balance;
    }

    // Getters and setters are generated by Lombok (@Getter / @Setter)
}
