package com.not_found.financial_planner_api.model;

import lombok.Getter;
import lombok.Setter;

/**
 * Represents a financial account in the system.
 * Uses Lombok annotations for automatic getter and setter generation.
 */
@Getter
@Setter
public class Account {
    public String subscriptionPlan; // true for Premium, false for Basic
    private String accountName; // Name of the account (e.g., "Checking", "Savings")
    private double balance; // Current balance of the account
    private String accountNumber; // Unique account number

    /** Default constructor for JPA and JSON serialization */
    public Account() {}

    /**
     * Constructor for creating a new account
     * @param name Name of the account (e.g., "Checking", "Savings")
     * @param balance Initial balance of the account
     */
    public Account(String accountNumber, String accountName, String subscriptionType, double balance) {
        this.balance = balance;
        this.accountName = accountName;
        this.subscriptionPlan = subscriptionType;
        this.accountNumber = accountNumber;
    }
    public String getSubscriptionPlan() {
    if (this.subscriptionPlan == null) {
        return "Basic"; // or return a default value
    }
    else {
        return this.subscriptionPlan;
}}}
        

    // Getters and setters are generated by Lombok (@Getter / @Setter)
