package com.not_found.financial_planner_api.model;

import java.util.List;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class AllDataResponse {
    private List<Account> accounts;
    private List<Transaction> transactions;
    private DashboardResponse dashboard;

    public AllDataResponse() {}

    public AllDataResponse(List<Account> accounts, List<Transaction> transactions, DashboardResponse dashboard) {
        this.accounts = accounts;
        this.transactions = transactions;
        this.dashboard = dashboard;
    }

    // Getters and setters are generated by Lombok (@Getter / @Setter)
}
