package com.not_found.financial_planner_api.model;

import java.util.List;
import java.util.Map;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class DashboardResponse {
    private List<Transaction> recent;
    private Map<String, Double> breakdown;
    private RewardsAnalysis.CardRecommendation bestCardRecommendation;
    private List<MonthlySpending> monthlySpending; // Last 6 months of spending

    public DashboardResponse() {}

    public DashboardResponse(List<Transaction> recent, Map<String, Double> breakdown, 
            RewardsAnalysis.CardRecommendation bestCardRecommendation,
            List<MonthlySpending> monthlySpending) {
        this.recent = recent;
        this.breakdown = breakdown;
        this.bestCardRecommendation = bestCardRecommendation;
        this.monthlySpending = monthlySpending;
    }

    // Getters and setters are generated by Lombok (@Getter / @Setter)
}
