package com.not_found.financial_planner_api.model;

import java.util.List;
import java.util.Map;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class DashboardResponse {
    private List<Transaction> recent;
    private Map<String, Double> breakdown;

    public DashboardResponse() {}

    public DashboardResponse(List<Transaction> recent, Map<String, Double> breakdown) {
        this.recent = recent;
        this.breakdown = breakdown;
    }

    // Getters and setters are generated by Lombok (@Getter / @Setter)
}
