package com.not_found.financial_planner_api.model;

import java.time.LocalDate;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Transaction {
    private long id;
    private long accountId;
    private LocalDate date;
    private String description;
    private double amount;

    public Transaction() {}

    public Transaction(long id, long accountId, LocalDate date, String description, double amount) {
        this.id = id;
        this.accountId = accountId;
        this.date = date;
        this.description = description;
        this.amount = amount;
    }

    // Getters and setters are generated by Lombok (@Getter / @Setter)
}
