package com.not_found.financial_planner_api.model;

import java.time.LocalDate;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents a financial transaction in the system.
 * Uses Lombok annotations for automatic getter and setter generation.
 */
@Getter
@Setter
public class Transaction {
    /** Unique identifier for the transaction */
    private String id;
    
    /** ID of the account this transaction belongs to */
    private String accountId;
    
    /** Date when the transaction occurred */
    private LocalDate date;
    
    /** Description or merchant name for the transaction */
    private String description;
    
    /** Transaction amount (positive for credits, negative for debits) */
    private double amount;

    /** Category of the transaction (e.g., "Dining", "Travel", etc.) */
    private String category;

    

    /** Default constructor for JPA and JSON serialization 
     * @param d 
     * @param string2 
     * @param localDate 
     * @param string 
     * @param i */
    /**
     * Constructor for creating a new transaction
     * @param id Unique identifier for the transaction
     * @param accountId ID of the account this transaction belongs to
     * @param date Date when the transaction occurred
     * @param description Description or merchant name
     * @param amount Transaction amount (positive for credits, negative for debits)
     */

    /**
     * Constructor for creating a new transaction with category
     * @param id Unique identifier for the transaction
     * @param accountId ID of the account this transaction belongs to
     * @param date Date when the transaction occurred
     * @param description Description or merchant name
     * @param amount Transaction amount (positive for credits, negative for debits)
     * @param category Category of the transaction
     */
    public Transaction() {}
    

    public Transaction(String id, String accountId, LocalDate date, String description, double amount) {
        this.id = id;
        this.accountId = accountId;
        this.date = date;
        this.description = description;
        this.amount = amount;
    }
   
    // Getters and setters are generated by Lombok (@Getter / @Setter)
}
